name: Compilar SA-MP

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Baixar compilador Pawn
        run: |
          git clone --depth 1 https://github.com/openmultiplayer/compiler.git compiler

      - name: Compilar racing.pwn
        run: |
          mkdir -p output
          mkdir -p compiler/build
          cd compiler/build
          cmake ../source/compiler
          cmake --build . --config Release
          cd ../..
          ./compiler/build/pawncc -i compiler/include gamemodes/racing.pwn -o output/racing.amx

      - name: Disponibilizar racing.amx
        uses: actions/upload-artifact@v4
        with:
          name: racing-amx
          path: output/racing.amx
